# Build
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /usr/app
COPY pom.xml /usr/app
RUN mvn dependency:go-offline
COPY src /usr/app/src

# Run
FROM maven:3.9.6-eclipse-temurin-21 AS dev
WORKDIR /usr/app
COPY --from=builder /usr/app/pom.xml /usr/app/pom.xml
COPY --from=builder /usr/app/src /usr/app/src

CMD ["mvn", "spring-boot:run"]