name: Deploy Credit API to VPS

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'docker-compose.yml'
      - 'Dockerfile.dev'
      - '!todo'
      - '!requirements.txt'
      - '!README.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: ${{ github.ref == 'refs/heads/main' && secrets.CREDIT_DB_USERNAME || secrets.CREDIT_DB_USERNAME_DEV }}
      SPRING_DATASOURCE_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.CREDIT_DB_PASSWORD || secrets.CREDIT_DB_PASSWORD_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./${{ github.ref == 'refs/heads/main' && 'Dockerfile' || 'Dockerfile.dev' }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/credit-api:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}

    - name: Copy Docker Compose file to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        source: "./docker-compose.${{ github.ref == 'refs/heads/main' && 'prod' || 'dev'}}"
        target: "."

    - name: Deploy Image ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SPRING_DATASOURCE_USERNAME: ${{ github.ref == 'refs/heads/main' && secrets.CREDIT_DB_USERNAME || secrets.CREDIT_DB_USERNAME_DEV }}
        SPRING_DATASOURCE_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.CREDIT_DB_PASSWORD || secrets.CREDIT_DB_PASSWORD_DEV }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        envs: DOCKER_USERNAME,SPRING_DATASOURCE_PASSWORD,SPRING_DATASOURCE_USERNAME
        script: |
          docker-compose -f docker-compose.${{ github.ref == 'refs/heads/main' && 'prod' || 'dev'}} pull
          docker-compose -f docker-compose.${{ github.ref == 'refs/heads/main' && 'prod' || 'dev'}} up -d